import React, { useState } from 'react';
import { GameQuestion } from '../types';
import { generateQuiz } from '../services/geminiService';
import { Trophy, Star, ArrowRight, Check, X, Gamepad2, Shuffle, Type } from 'lucide-react';

interface GameArenaProps {
    addXP: (amount: number, description: string) => void;
}

type GameMode = 'hub' | 'trivia' | 'scramble' | 'hangman';

// --- OFFLINE DATA ---
const SCRAMBLE_WORDS = [
    { word: 'COMPUTER', hint: 'An electronic device for working' },
    { word: 'ELEPHANT', hint: 'A very large animal with a trunk' },
    { word: 'TEACHER', hint: 'Someone who helps you learn' },
    { word: 'LIBRARY', hint: 'A place full of books' },
    { word: 'SUMMER', hint: 'The hottest season' },
    { word: 'FRIEND', hint: 'Someone you like to play with' },
    { word: 'BREAKFAST', hint: 'The first meal of the day' },
    { word: 'HOSPITAL', hint: 'Where you go when you are sick' }
];

const HANGMAN_WORDS = ['APPLES', 'BANANA', 'CHERRY', 'DOCTOR', 'FAMILY', 'GARDEN', 'HOUSE', 'IGLOO', 'JACKET', 'KITTEN', 'LEMON', 'MONKEY', 'NIGHT', 'ORANGE', 'PENCIL', 'QUEEN', 'RABBIT', 'SCHOOL', 'TIGER', 'UMBRELLA', 'VIOLIN', 'WATER', 'YELLOW', 'ZEBRA'];

export const GameArena: React.FC<GameArenaProps> = ({ addXP }) => {
    const [mode, setMode] = useState<GameMode>('hub');
    
    // TRIVIA STATE
    const [topic, setTopic] = useState('Animals');
    const [questions, setQuestions] = useState<GameQuestion[]>([]);
    const [currentQIndex, setCurrentQIndex] = useState(0);
    const [score, setScore] = useState(0);
    const [loading, setLoading] = useState(false);
    const [selectedOption, setSelectedOption] = useState<string | null>(null);
    const [showFeedback, setShowFeedback] = useState(false);

    // SCRAMBLE STATE
    const [scrambleIndex, setScrambleIndex] = useState(0);
    const [scrambleInput, setScrambleInput] = useState('');
    const [scrambleFeedback, setScrambleFeedback] = useState<'none' | 'correct' | 'wrong'>('none');

    // HANGMAN STATE
    const [hangmanWord, setHangmanWord] = useState('');
    const [guessedLetters, setGuessedLetters] = useState<string[]>([]);
    const [hangmanGameStatus, setHangmanGameStatus] = useState<'playing' | 'won' | 'lost'>('playing');

    const triviaTopics = ['Animals', 'Food', 'Travel', 'School', 'Colors'];

    // --- GAME HUB ---
    if (mode === 'hub') {
        return (
            <div className="h-full p-6 md:p-10 overflow-y-auto">
                <header className="mb-10">
                    <h2 className="text-3xl font-extrabold text-slate-800">Game Playground</h2>
                    <p className="text-slate-500">Fun ways to learn English!</p>
                </header>
                
                <div className="grid md:grid-cols-3 gap-6">
                    {/* Game 1: AI Trivia */}
                    <button onClick={() => setMode('trivia')} className="bg-white p-6 rounded-3xl border-2 border-slate-100 hover:border-brand-400 hover:shadow-xl transition-all text-left group">
                        <div className="w-16 h-16 bg-blue-100 rounded-2xl flex items-center justify-center text-blue-600 mb-4 group-hover:scale-110 transition-transform">
                            <Star className="w-8 h-8" />
                        </div>
                        <h3 className="text-xl font-bold text-slate-800 mb-2">AI Quiz Master</h3>
                        <p className="text-slate-500 text-sm">Challenge yourself with questions generated by AI.</p>
                        <div className="mt-4 inline-block px-3 py-1 bg-blue-50 text-blue-600 rounded-full text-xs font-bold">Online Required</div>
                    </button>

                    {/* Game 2: Word Scramble */}
                    <button onClick={() => setMode('scramble')} className="bg-white p-6 rounded-3xl border-2 border-slate-100 hover:border-brand-400 hover:shadow-xl transition-all text-left group">
                         <div className="w-16 h-16 bg-purple-100 rounded-2xl flex items-center justify-center text-purple-600 mb-4 group-hover:scale-110 transition-transform">
                            <Shuffle className="w-8 h-8" />
                        </div>
                        <h3 className="text-xl font-bold text-slate-800 mb-2">Word Scramble</h3>
                        <p className="text-slate-500 text-sm">Unscramble the mixed-up letters to find the word.</p>
                        <div className="mt-4 inline-block px-3 py-1 bg-green-50 text-green-600 rounded-full text-xs font-bold">Offline Play</div>
                    </button>

                    {/* Game 3: Hangman */}
                    <button onClick={() => {
                        setHangmanWord(HANGMAN_WORDS[Math.floor(Math.random() * HANGMAN_WORDS.length)]);
                        setGuessedLetters([]);
                        setHangmanGameStatus('playing');
                        setMode('hangman');
                    }} className="bg-white p-6 rounded-3xl border-2 border-slate-100 hover:border-brand-400 hover:shadow-xl transition-all text-left group">
                         <div className="w-16 h-16 bg-orange-100 rounded-2xl flex items-center justify-center text-orange-600 mb-4 group-hover:scale-110 transition-transform">
                            <Type className="w-8 h-8" />
                        </div>
                        <h3 className="text-xl font-bold text-slate-800 mb-2">Word Guess</h3>
                        <p className="text-slate-500 text-sm">Guess the letters before you run out of chances!</p>
                        <div className="mt-4 inline-block px-3 py-1 bg-green-50 text-green-600 rounded-full text-xs font-bold">Offline Play</div>
                    </button>
                </div>
            </div>
        );
    }

    // --- GAME: WORD SCRAMBLE ---
    if (mode === 'scramble') {
        const current = SCRAMBLE_WORDS[scrambleIndex % SCRAMBLE_WORDS.length];
        const scrambled = current.word.split('').sort(() => Math.random() - 0.5).join('');

        const checkScramble = () => {
            if (scrambleInput.toUpperCase().trim() === current.word) {
                setScrambleFeedback('correct');
                addXP(20, "Won Word Scramble");
                setTimeout(() => {
                    setScrambleIndex(prev => prev + 1);
                    setScrambleInput('');
                    setScrambleFeedback('none');
                }, 1500);
            } else {
                setScrambleFeedback('wrong');
            }
        };

        return (
            <div className="h-full flex flex-col items-center justify-center p-6 bg-purple-50">
                 <button onClick={() => setMode('hub')} className="absolute top-6 left-6 text-slate-400 font-bold hover:text-purple-600">Back to Games</button>
                 
                 <div className="bg-white p-10 rounded-3xl shadow-xl text-center max-w-md w-full border border-purple-100">
                     <h2 className="text-2xl font-bold text-slate-800 mb-2">Word Scramble</h2>
                     <p className="text-slate-500 mb-8">Unscramble the letters!</p>
                     
                     <div className="text-4xl font-black text-purple-600 tracking-widest mb-4 bg-purple-50 py-4 rounded-xl">
                         {scrambleFeedback === 'correct' ? current.word : scrambled}
                     </div>
                     
                     <p className="text-sm font-bold text-slate-400 mb-6 uppercase tracking-wider">Hint: {current.hint}</p>
                     
                     <input 
                        type="text" 
                        value={scrambleInput}
                        onChange={(e) => setScrambleInput(e.target.value)}
                        className="w-full text-center border-2 border-slate-200 rounded-xl p-3 text-xl font-bold mb-4 focus:border-purple-500 outline-none uppercase"
                        placeholder="Type answer here"
                     />
                     
                     <button 
                        onClick={checkScramble}
                        className={`w-full py-3 rounded-xl font-bold text-white transition-all ${scrambleFeedback === 'correct' ? 'bg-green-500' : scrambleFeedback === 'wrong' ? 'bg-red-500' : 'bg-purple-600'}`}
                     >
                         {scrambleFeedback === 'correct' ? 'Correct!' : scrambleFeedback === 'wrong' ? 'Try Again' : 'Check'}
                     </button>
                 </div>
            </div>
        );
    }

    // --- GAME: HANGMAN ---
    if (mode === 'hangman') {
        const maxWrong = 6;
        const wrongGuesses = guessedLetters.filter(l => !hangmanWord.includes(l)).length;
        const remaining = maxWrong - wrongGuesses;
        
        const isWon = hangmanWord.split('').every(l => guessedLetters.includes(l));
        const isLost = remaining <= 0;

        const guessLetter = (l: string) => {
            if (isWon || isLost || guessedLetters.includes(l)) return;
            const newGuessed = [...guessedLetters, l];
            setGuessedLetters(newGuessed);
            
            // Check win/loss immediately
            const wrongCount = newGuessed.filter(char => !hangmanWord.includes(char)).length;
            const hasWon = hangmanWord.split('').every(char => newGuessed.includes(char));
            
            if (hasWon) {
                setHangmanGameStatus('won');
                addXP(30, "Won Word Guess");
            } else if ((maxWrong - wrongCount) <= 0) {
                setHangmanGameStatus('lost');
            }
        };

        const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

        return (
            <div className="h-full flex flex-col items-center justify-center p-6 bg-orange-50">
                <button onClick={() => setMode('hub')} className="absolute top-6 left-6 text-slate-400 font-bold hover:text-orange-600">Back to Games</button>

                <div className="bg-white p-8 rounded-3xl shadow-xl text-center max-w-lg w-full">
                     <h2 className="text-xl font-bold text-slate-800 mb-4">Word Guess</h2>
                     
                     <div className="mb-8 font-mono text-4xl tracking-widest space-x-2 text-slate-800 font-bold">
                         {hangmanWord.split('').map((l, i) => (
                             <span key={i} className="border-b-4 border-slate-300 min-w-[30px] inline-block">
                                 {guessedLetters.includes(l) || isLost ? l : ''}
                             </span>
                         ))}
                     </div>
                     
                     <div className="mb-6 flex justify-center gap-8">
                         <div className="text-center">
                             <div className="text-3xl font-bold text-red-500">{remaining}</div>
                             <div className="text-xs font-bold text-slate-400 uppercase">Chances Left</div>
                         </div>
                     </div>

                     <div className="grid grid-cols-7 gap-2 mb-6">
                         {alphabet.map(l => {
                             const isGuessed = guessedLetters.includes(l);
                             const isInWord = hangmanWord.includes(l);
                             let btnClass = "bg-slate-100 text-slate-700 hover:bg-slate-200";
                             if (isGuessed) {
                                 btnClass = isInWord ? "bg-green-500 text-white" : "bg-slate-300 text-slate-400";
                             }
                             return (
                                 <button 
                                    key={l}
                                    onClick={() => guessLetter(l)}
                                    disabled={isGuessed || isWon || isLost}
                                    className={`w-10 h-10 rounded-lg font-bold transition-colors ${btnClass}`}
                                 >
                                     {l}
                                 </button>
                             );
                         })}
                     </div>

                     {(isWon || isLost) && (
                         <div className="animate-fade-in">
                             <div className={`text-2xl font-black mb-4 ${isWon ? 'text-green-500' : 'text-red-500'}`}>
                                 {isWon ? 'YOU WON!' : 'GAME OVER'}
                             </div>
                             <button 
                                onClick={() => {
                                    setHangmanWord(HANGMAN_WORDS[Math.floor(Math.random() * HANGMAN_WORDS.length)]);
                                    setGuessedLetters([]);
                                    setHangmanGameStatus('playing');
                                }}
                                className="px-8 py-3 bg-orange-500 text-white rounded-xl font-bold shadow-lg hover:bg-orange-600 transition-transform hover:scale-105"
                             >
                                 Play Again
                             </button>
                         </div>
                     )}
                </div>
            </div>
        );
    }

    // --- GAME: TRIVIA (Legacy AI Game) ---
    const startTrivia = async (selectedTopic: string) => {
        setLoading(true);
        setTopic(selectedTopic);
        setScore(0);
        setCurrentQIndex(0);
        setSelectedOption(null);
        setShowFeedback(false);
        try {
            const qs = await generateQuiz(selectedTopic);
            setQuestions(qs);
        } catch (e) {
            console.error(e);
        } finally {
            setLoading(false);
        }
    };

    if (mode === 'trivia' && questions.length === 0 && !loading) {
        return (
            <div className="h-full p-8 flex flex-col items-center justify-center bg-blue-50">
                 <button onClick={() => setMode('hub')} className="absolute top-6 left-6 text-slate-400 font-bold hover:text-blue-600">Back to Games</button>
                 <div className="w-20 h-20 bg-white rounded-2xl shadow-lg mx-auto mb-6 flex items-center justify-center -rotate-6">
                     <Star className="w-10 h-10 text-blue-500" />
                 </div>
                 <h2 className="text-3xl font-extrabold text-slate-800">Quiz Master</h2>
                 <p className="text-slate-500 mb-8">Pick a topic to generate a new quiz!</p>
                 <div className="grid grid-cols-2 gap-4 w-full max-w-md">
                    {triviaTopics.map(t => (
                        <button 
                            key={t}
                            onClick={() => startTrivia(t)}
                            className="bg-white p-4 rounded-xl shadow-sm border-2 border-transparent hover:border-blue-400 hover:shadow-md transition-all font-bold text-slate-700 flex items-center justify-between group"
                        >
                            {t}
                            <ArrowRight className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity text-blue-500" />
                        </button>
                    ))}
                </div>
            </div>
        );
    }

    if (loading) {
         return (
            <div className="flex flex-col items-center justify-center h-full space-y-4">
                <div className="w-16 h-16 border-4 border-blue-200 border-t-blue-500 rounded-full animate-spin"></div>
                <p className="text-slate-500 font-bold">Generating questions...</p>
            </div>
        );
    }

    if (mode === 'trivia' && questions.length > 0) {
        // Trivia render logic (simplified for brevity, similar to previous implementation but using new layout)
        const currentQ = questions[currentQIndex];
        const isFinished = currentQIndex >= questions.length;

        if (isFinished) {
             return (
                <div className="h-full flex flex-col items-center justify-center p-6 text-center">
                    <Trophy className="w-24 h-24 text-yellow-400 mb-4" />
                    <h2 className="text-3xl font-bold">Quiz Complete!</h2>
                    <p className="text-xl mb-6">Score: {score}/{questions.length}</p>
                    <button onClick={() => setQuestions([])} className="bg-blue-500 text-white px-6 py-3 rounded-xl font-bold">New Quiz</button>
                </div>
             );
        }

        const handleAnswer = (opt: string) => {
            if (selectedOption) return;
            setSelectedOption(opt);
            setShowFeedback(true);
            if(opt === currentQ.correctAnswer) {
                setScore(s => s+1);
                addXP(10, "Trivia Correct Answer");
            }
            setTimeout(() => {
                if(currentQIndex < questions.length) {
                    setCurrentQIndex(prev => prev + 1);
                    setSelectedOption(null);
                    setShowFeedback(false);
                }
            }, 2000);
        };

        return (
            <div className="h-full flex flex-col p-6 max-w-2xl mx-auto">
                 <button onClick={() => setMode('hub')} className="self-start text-slate-400 font-bold mb-4">Exit Quiz</button>
                 <h3 className="text-xl font-bold mb-6">Question {currentQIndex+1}/{questions.length}</h3>
                 <p className="text-2xl font-bold text-slate-800 mb-8">{currentQ.question}</p>
                 <div className="space-y-3">
                     {currentQ.options.map(opt => {
                         let style = "bg-white border-2 border-slate-200";
                         if(selectedOption === opt) {
                             style = opt === currentQ.correctAnswer ? "bg-green-100 border-green-500 text-green-700" : "bg-red-100 border-red-500 text-red-700";
                         } else if (showFeedback && opt === currentQ.correctAnswer) {
                             style = "bg-green-50 border-green-300 text-green-700";
                         }
                         return (
                             <button key={opt} onClick={() => handleAnswer(opt)} disabled={!!selectedOption} className={`w-full p-4 rounded-xl text-left font-bold ${style}`}>
                                 {opt}
                             </button>
                         )
                     })}
                 </div>
            </div>
        );
    }

    return null;
};